# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9cfa3c21dad180a6e9bc2f70d15a058b61d7ad1c43f70a660dd15b221825dd9450575cc2abc8ac090c1879d30edacafe3b7d6eb4bb3df4054f4c9fd61ab9dd3

test:
  secret_key_base: e96ab712877c17faacd838a557cb51120430dface1d7a90e826bbf1e358844223c634922a8d32da939116b20ecc3a11ab1dfdfda0a839f1a789dd184bb278033

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
